/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'smandal' at '8/18/15 4:26 PM' with Gradle 2.6
 *
 * @author smandal, @date 8/18/15 4:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
