import org.junit.Test;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.alwaid.email_component.bean.EmailBean;
import com.alwaid.email_component.bean.IEmailBean;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'HP' at '8/24/15 8:48 PM' with Gradle 2.5
 *
 * @author HP, @date 8/24/15 8:48 PM
 */
public class EmailServiceTest {
	@Test
	public void testEmailService() {
		ApplicationContext context = new ClassPathXmlApplicationContext(
				"classpath*:**/applicationContext*.xml");
		IEmailBean emailBean = context.getBean(EmailBean.class);
		emailBean.setTOs("mail2soumit@gmail.com");
		emailBean.setSubject("Hello from jUnit");
		emailBean.setBody("Testing by jUnit");

		assertTrue("Mail should successfully sent", emailBean.sendMail());
	}
}
